function changelog {
LOGPATH="/usr/lib/node_modules/@treehouses/cli/CHANGELOG.md"
view <(grep -e '[->#]\+' -e ^$ $LOGPATH | sed '3d;4d;5d;')
}
function changelog_help {
  CYAN='\033[1;36m'
  NC='\033[0m' #no color
  echo
  echo "  Usage: $BASENAME changelog"
  echo
  echo "  Views the treehouses changelog generated by auto-changelog."
  echo
  echo "  Example: $BASENAME changelog"
  echo
  echo -e "  ${CYAN}### Changelog"
  echo
  echo "  #### [1.20.22](https://github.com/treehouses/cli/compare/1.20.21...1.20.22)"
  echo
  echo -e "  ${NC}> 12 May 2020"
  echo
  echo "  - \`treehouses services privatebin icon refactor\` [\`#1254\`](https://github.com/treehouses/cli/pull/1254)"
  echo
  echo -e "  ${CYAN}#### [1.20.21](https://github.com/treehouses/cli/compare/1.20.20...1.20.21)"
  echo
  echo -e "  ${NC}> 12 May 2020"
  echo
  echo "  - \`treehouses services mariadb icon refactor\` [\`#1255\`](https://github.com/treehouses/cli/pull/1255)"
  echo
}
