#!/bin/bash

_treehouses_complete()
{
  local cur prev

  # Valid top-level completions
  commands="ap aphidden apchannel blocker bluetooth bluetoothid bootoption bridge burn button camera clone \
            container coralenv cron default detect detectbluetooth detectrpi discover ethernet expandfs \
            feedback help image internet led locale log memory networkmode ntp openvpn password \
            rebootneeded reboots rename remote restore rtc sdbench services speedtest ssh sshkey sshtunnel \
            staticwifi temperature timezone tor upgrade usb verbose version vnc wifi wificountry wifihidden wifistatus"
  ap_cmds="local internet"
  aphidden_cmds="local internet"
  apchannel_cmds="1 2 3 4 5 6 7 8 9 10 11"
  blocker_cmds="0 1 2 3 4 max"
  bluetooth_cmds="on off pause mac id button"
  bootoption_cmds="console desktop"
  button_cmds="off bluetooth"
  camera_cmds="on off capture"
  container_cmds="none docker balena"
  coralenv_cmds="install demo-on demo-off demo-always-on"
  cron_cmds="list 0W tor timestamp add delete deleteall"
  discover_cmds="rpi scan interface ping ports mac"
  detectrpi_cmds="model"
  help_cmds=$commands
  led_cmds="green red dance thanksgiving christmas newyear lunarnewyear valentine carnival onam"
  log_cmds="0 1 2 3 4 show max"
  memory_cmds="total used free"
  networkmode_cmds="info"
  ntp_cmds="local internet"
  openvpn_cmds="use show delete notice start stop load"
  reboots_cmds="now in cron daily weekly monthly"
  rtc_cmds="on off"
  services_cmds="available installed running ports kolibri mastodon moodle netdata nextcloud ntopng pihole planet portainer privatebin couchdb mariadb"
  sshkey_cmds="add list delete deleteall github addgithubusername deletegithubusername addgithubgroup"
  ssh_cmds="on off"
  sshtunnel_cmds="add remove list key notice check"
  temperature_cmds="celsius fahrenheit"
  tor_cmds="list add delete deleteall start stop destroy notice status refresh"
  usb_cmds="on off"
  remote_cmds="status upgrade services version"
  verbose_cmds="on off"
  vnc_cmds="on off info"

  notice_cmds="on off add delete list now"
  rtc_second_cmds="ds3231 rasclock"
  bluetooth_second_cmds="number"
  bootoption_second_cmds="autologin"
  led_second_cmds="heartbeat default-on oneshot timer cpu0 gpio input backlight none kbd"
  services_second_cmds="full"
  services_second_cmds2="install up down start stop restart autorun ps info url port size"
  sshkey_second_cmds="adduser deleteuser addteam"
  remote_second_cmds="available installed running"

  services_third_cmds="true false"
  services_third_cmds2="local tor both"

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  if [ $COMP_CWORD -eq 1 ]
  then
    COMPREPLY=( $(compgen -W "${commands}" -- $cur) )
  elif [ $COMP_CWORD -eq 2 ]
  then
    case "$prev" in
      "ap")
        COMPREPLY=( $(compgen -W "$ap_cmds" -- $cur) )
        ;;
      "aphidden")
        COMPREPLY=( $(compgen -W "$aphidden_cmds" -- $cur) )
        ;;
      "apchannel")
        COMPREPLY=( $(compgen -W "$apchannel_cmds" -- $cur) ) #cannot ascending order
        ;;
      "blocker")
        COMPREPLY=( $(compgen -W "$blocker_cmds" -- $cur) )
        ;;
      "bluetooth")
        COMPREPLY=( $(compgen -W "$bluetooth_cmds" -- $cur) )
        ;;
      "bootoption")
        COMPREPLY=( $(compgen -W "$bootoption_cmds" -- $cur) )
        ;;
      "button")
        COMPREPLY=( $(compgen -W "$button_cmds" -- $cur) )
        ;;
      "camera")
        COMPREPLY=( $(compgen -W "$camera_cmds" -- $cur) )
        ;;
      "container")
        COMPREPLY=( $(compgen -W "$container_cmds" -- $cur) )
        ;;
      "coralenv")
        COMPREPLY=( $(compgen -W "$coralenv_cmds" -- $cur) )
        ;;
      "cron")
        COMPREPLY=( $(compgen -W "$cron_cmds" -- $cur) )
        ;;
      "discover")
        COMPREPLY=( $(compgen -W "$discover_cmds" -- $cur) )
        ;;
      "detectrpi")
        COMPREPLY=( $(compgen -W "$detectrpi_cmds" -- $cur) )
        ;;
      "help")
        COMPREPLY=( $(compgen -W "$help_cmds" -- $cur) )
        ;;
      "led")
        COMPREPLY=( $(compgen -W "$led_cmds" -- $cur) )
        ;;
      "memory")
        COMPREPLY=( $(compgen -W "$memory_cmds" -- $cur) )
        ;;
      "networkmode")
        COMPREPLY=( $(compgen -W "$networkmode_cmds" -- $cur) )
        ;;
      "ntp")
        COMPREPLY=( $(compgen -W "$ntp_cmds" -- $cur) )
        ;;
      "openvpn")
        COMPREPLY=( $(compgen -W "$openvpn_cmds" -- $cur) )
        ;;
      "rtc")
        COMPREPLY=( $(compgen -W "$rtc_cmds" -- $cur) )
        ;;
      "reboots")
        COMPREPLY=( $(compgen -W "$reboots_cmds" -- $cur) )
        ;;
      "services")
        COMPREPLY=( $(compgen -W "$services_cmds" -- $cur) )
        ;;
      "sshkey")
        COMPREPLY=( $(compgen -W "$sshkey_cmds" -- $cur) )
        ;;
      "ssh")
        COMPREPLY=( $(compgen -W "$ssh_cmds" -- $cur) )
        ;;
      "sshtunnel")
        COMPREPLY=( $(compgen -W "$sshtunnel_cmds" -- $cur) )
        ;;
      "temperature")
        COMPREPLY=( $(compgen -W "$temperature_cmds" -- $cur) )
        ;;
      "tor")
        COMPREPLY=( $(compgen -W "$tor_cmds" -- $cur) )
        ;;
      "verbose")
        COMPREPLY=( $(compgen -W "$verbose_cmds" -- $cur) )
        ;;
      "log")
        COMPREPLY=( $(compgen -W "$log_cmds" -- $cur) )
        ;;
      "usb")
        COMPREPLY=( $(compgen -W "$usb_cmds" -- $cur) )
        ;;
      "vnc")
        COMPREPLY=( $(compgen -W "$vnc_cmds" -- $cur) )
        ;;
      "remote")
        COMPREPLY=( $(compgen -W "$remote_cmds" -- $cur) )
        ;;
      "*")
        ;;
    esac
  elif [ $COMP_CWORD -eq 3 ]
  then
    case "$prev" in
      "console"|"desktop")
        COMPREPLY=( $(compgen -W "$bootoption_second_cmds" -- $cur) )
        ;;
      "notice")
        COMPREPLY=( $(compgen -W "$notice_cmds" -- $cur) )
        ;;
      "on")
        COMPREPLY=( $(compgen -W "$rtc_second_cmds" -- $cur) )
        ;;
      "id")
        COMPREPLY=( $(compgen -W "$bluetooth_second_cmds" -- $cur) )
        ;;
      "green"|"red")
        COMPREPLY=( $(compgen -W "$led_second_cmds" -- $cur) )
        ;;
      "available"|"installed"|"running")
        COMPREPLY=( $(compgen -W "$services_second_cmds" -- $cur) )
        ;;
      "planet"|"kolibri"|"nextcloud"|"netdata"|"mastodon"|"moodle"|"pihole"|"privatebin"|"portainer"|"ntopng"|"couchdb"|"mariadb")
        COMPREPLY=( $(compgen -W "$services_second_cmds2" -- $cur) )
        ;;
      "github")
        COMPREPLY=( $(compgen -W "$sshkey_second_cmds" -- $cur) )
        ;;
      "services")
        COMPREPLY=( $(compgen -W "$remote_second_cmds" -- $cur) )
        ;;
      "*")
        ;;
    esac
  elif [ $COMP_CWORD -eq 4 ]
  then
    case "$prev" in
      "autorun")
        COMPREPLY=( $(compgen -W "$services_third_cmds" -- $cur) )
        ;;
      "url")
        COMPREPLY=( $(compgen -W "$services_third_cmds2" -- $cur) )
        ;;
      "*")
        ;;
    esac
  fi
  every_command=""
  read -r -d '' every_command <<'EOF'
treehouses ap local
treehouses ap internet
treehouses apchannel
treehouses aphidden local
treehouses aphidden internet
treehouses blocker
treehouses blocker max
treehouses blocker 4
treehouses blocker 3
treehouses blocker 2
treehouses blocker 1
treehouses blocker 0
treehouses bluetooth off
treehouses bluetooth pause
treehouses bluetooth on
treehouses bluetooth mac
treehouses bluetooth id
treehouses bluetooth id number
treehouses bluetooth button
treehouses bluetoothid
treehouses bluetoothid number
treehouses bootoption console
treehouses bootoption console autologin
treehouses bootoption desktop
treehouses bootoption desktop autologin
treehouses bridge
treehouses burn
treehouses button off
treehouses button bluetooth
treehouses camera
treehouses camera on
treehouses camera off
treehouses camera capture
treehouses clone
treehouses container
treehouses container balena
treehouses container none
treehouses container docker
treehouses coralenv install
treehouses coralenv demo-on
treehouses coralenv demo-always-on
treehouses coralenv demo-off
treehouses cron
treehouses cron add
treehouses cron delete
treehouses cron deleteall
treehouses cron tor
treehouses cron timestamp
treehouses cron 0W
treehouses cron list
treehouses default
treehouses default network
treehouses default tunnel
treehouses default notice
treehouses detect
treehouses detectrpi
treehouses detectrpi model
treehouses detectbluetooth
treehouses discover rpi
treehouses discover scan google.com
treehouses discover scan scanme.nmap.org
treehouses discover interface
treehouses discover ping google.com
treehouses discover ports localhost
treehouses discover mac b8:29:eb:9f:42:8b
treehouses ethernet
treehouses expandfs
treehouses feedback
treehouses help
treehouses help apchannel
treehouses help aphidden
treehouses help ap
treehouses help blocker
treehouses help bluetoothid
treehouses help bluetooth
treehouses help bootoption
treehouses help bridge
treehouses help burn
treehouses help button
treehouses help camera
treehouses help clone
treehouses help container
treehouses help coralenv
treehouses help cron
treehouses help default
treehouses help detectrpi
treehouses help detect
treehouses help discover
treehouses help ethernet
treehouses help expandfs
treehouses help feedback
treehouses help image
treehouses help internet
treehouses help led
treehouses help locale
treehouses help log
treehouses help memory
treehouses help networkmode
treehouses help ntp
treehouses help openvpn
treehouses help password
treehouses help rebootneeded
treehouses help reboots
treehouses help remote
treehouses help rename
treehouses help restore
treehouses help rtc
treehouses help sdbench
treehouses help services
treehouses help speedtest
treehouses help sshkey
treehouses help ssh
treehouses help sshtunnel
treehouses help staticwifi
treehouses help temperature
treehouses help timezone
treehouses help tor
treehouses help upgrade
treehouses help usb
treehouses help verbose
treehouses help version
treehouses help vnc
treehouses help wificountry
treehouses help wifihidden
treehouses help wifi
treehouses help wifistatus
treehouses image
treehouses internet
treehouses led green heartbeat
treehouses led red default-on
treehouses led
treehouses led green
treehouses led red
treehouses led dance
treehouses led thanksgiving
treehouses led christmas
treehouses led lunarnewyear
treehouses led valentine
treehouses led carnival
treehouses led onam
treehouses led newyear
treehouses locale
treehouses log
treehouses log max
treehouses log 4
treehouses log 3
treehouses log 2
treehouses log 1
treehouses log 0
treehouses log show
treehouses log show 5
treehouses memory -g
treehouses memory -m
treehouses memory
treehouses memory total -g
treehouses memory total -m
treehouses memory total
treehouses memory used -g
treehouses memory used -m
treehouses memory used
treehouses memory free -g
treehouses memory free -m
treehouses memory free
treehouses networkmode
treehouses networkmode info
treehouses ntp local
treehouses ntp internet
treehouses openvpn
treehouses openvpn use
treehouses openvpn show
treehouses openvpn delete
treehouses openvpn start
treehouses openvpn stop
treehouses openvpn load
treehouses openvpn notice
treehouses openvpn notice on
treehouses openvpn notice add
treehouses openvpn notice delete
treehouses openvpn notice list
treehouses openvpn notice off
treehouses password
treehouses services available
treehouses services available full
treehouses services installed
treehouses services installed full
treehouses services running
treehouses services running full
treehouses services ports
treehouses services kolibri info
treehouses services kolibri install
treehouses services kolibri up
treehouses services kolibri restart
treehouses services kolibri port
treehouses services kolibri ps
treehouses services kolibri url
treehouses services kolibri url local
treehouses services kolibri url tor
treehouses services kolibri url both
treehouses services kolibri autorun
treehouses services kolibri autorun true
treehouses services kolibri autorun false
treehouses services kolibri start
treehouses services kolibri stop
treehouses services kolibri down
treehouses services kolibri cleanup
treehouses services kolibri icon
treehouses services kolibri size
treehouses services couchdb info
treehouses services couchdb install
treehouses services couchdb up
treehouses services couchdb restart
treehouses services couchdb port
treehouses services couchdb ps
treehouses services couchdb url
treehouses services couchdb url local
treehouses services couchdb url tor
treehouses services couchdb url both
treehouses services couchdb autorun
treehouses services couchdb autorun true
treehouses services couchdb autorun false
treehouses services couchdb start
treehouses services couchdb stop
treehouses services couchdb down
treehouses services couchdb cleanup
treehouses services couchdb icon
treehouses services couchdb size
treehouses services mariadb info
treehouses services mariadb install
treehouses services mariadb up
treehouses services mariadb restart
treehouses services mariadb port
treehouses services mariadb ps
treehouses services mariadb url
treehouses services mariadb url local
treehouses services mariadb url tor
treehouses services mariadb url both
treehouses services mariadb autorun
treehouses services mariadb autorun true
treehouses services mariadb autorun false
treehouses services mariadb start
treehouses services mariadb stop
treehouses services mariadb down
treehouses services mariadb cleanup
treehouses services mariadb icon
treehouses services mariadb size
treehouses services mastodon info
treehouses services mastodon install
treehouses services mastodon up
treehouses services mastodon restart
treehouses services mastodon port
treehouses services mastodon ps
treehouses services mastodon url
treehouses services mastodon url local
treehouses services mastodon url tor
treehouses services mastodon url both
treehouses services mastodon autorun
treehouses services mastodon autorun true
treehouses services mastodon autorun false
treehouses services mastodon start
treehouses services mastodon stop
treehouses services mastodon down
treehouses services mastodon cleanup
treehouses services mastodon icon
treehouses services mastodon size
treehouses services moodle info
treehouses services moodle install
treehouses services moodle up
treehouses services moodle restart
treehouses services moodle port
treehouses services moodle ps
treehouses services moodle url
treehouses services moodle url local
treehouses services moodle url tor
treehouses services moodle url both
treehouses services moodle autorun
treehouses services moodle autorun true
treehouses services moodle autorun false
treehouses services moodle start
treehouses services moodle stop
treehouses services moodle down
treehouses services moodle cleanup
treehouses services moodle icon
treehouses services moodle size
treehouses services netdata info
treehouses services netdata install
treehouses services netdata up
treehouses services netdata restart
treehouses services netdata port
treehouses services netdata ps
treehouses services netdata url
treehouses services netdata url local
treehouses services netdata url tor
treehouses services netdata url both
treehouses services netdata autorun
treehouses services netdata autorun true
treehouses services netdata autorun false
treehouses services netdata start
treehouses services netdata stop
treehouses services netdata down
treehouses services netdata cleanup
treehouses services netdata icon
treehouses services netdata size
treehouses services nextcloud info
treehouses services nextcloud install
treehouses services nextcloud up
treehouses services nextcloud restart
treehouses services nextcloud port
treehouses services nextcloud ps
treehouses services nextcloud url
treehouses services nextcloud url local
treehouses services nextcloud url tor
treehouses services nextcloud url both
treehouses services nextcloud autorun
treehouses services nextcloud autorun true
treehouses services nextcloud autorun false
treehouses services nextcloud start
treehouses services nextcloud stop
treehouses services nextcloud down
treehouses services nextcloud cleanup
treehouses services nextcloud icon
treehouses services nextcloud size
treehouses services ntopng info
treehouses services ntopng install
treehouses services ntopng up
treehouses services ntopng restart
treehouses services ntopng port
treehouses services ntopng ps
treehouses services ntopng url
treehouses services ntopng url local
treehouses services ntopng url tor
treehouses services ntopng url both
treehouses services ntopng autorun
treehouses services ntopng autorun true
treehouses services ntopng autorun false
treehouses services ntopng start
treehouses services ntopng stop
treehouses services ntopng down
treehouses services ntopng cleanup
treehouses services ntopng icon
treehouses services ntopng size
treehouses services pihole info
treehouses services pihole install
treehouses services pihole up
treehouses services pihole restart
treehouses services pihole port
treehouses services pihole ps
treehouses services pihole url
treehouses services pihole url local
treehouses services pihole url tor
treehouses services pihole url both
treehouses services pihole autorun
treehouses services pihole autorun true
treehouses services pihole autorun false
treehouses services pihole start
treehouses services pihole stop
treehouses services pihole down
treehouses services pihole cleanup
treehouses services pihole icon
treehouses services pihole size
treehouses services portainer info
treehouses services portainer install
treehouses services portainer up
treehouses services portainer restart
treehouses services portainer port
treehouses services portainer ps
treehouses services portainer url
treehouses services portainer url local
treehouses services portainer url tor
treehouses services portainer url both
treehouses services portainer autorun
treehouses services portainer autorun true
treehouses services portainer autorun false
treehouses services portainer start
treehouses services portainer stop
treehouses services portainer down
treehouses services portainer cleanup
treehouses services portainer icon
treehouses services portainer size
treehouses services privatebin info
treehouses services privatebin install
treehouses services privatebin up
treehouses services privatebin restart
treehouses services privatebin port
treehouses services privatebin ps
treehouses services privatebin url
treehouses services privatebin url local
treehouses services privatebin url tor
treehouses services privatebin url both
treehouses services privatebin autorun
treehouses services privatebin autorun true
treehouses services privatebin autorun false
treehouses services privatebin start
treehouses services privatebin stop
treehouses services privatebin down
treehouses services privatebin cleanup
treehouses services privatebin icon
treehouses services privatebin size
treehouses services planet info
treehouses services planet install
treehouses services planet up
treehouses services planet restart
treehouses services planet port
treehouses services planet ps
treehouses services planet url
treehouses services planet url local
treehouses services planet url tor
treehouses services planet url both
treehouses services planet autorun
treehouses services planet autorun true
treehouses services planet autorun false
treehouses services planet start
treehouses services planet stop
treehouses services planet down
treehouses services planet cleanup
treehouses services planet icon
treehouses services planet size
treehouses rebootneeded
treehouses reboots
treehouses reboots now
treehouses reboots in
treehouses reboots daily
treehouses reboots weekly
treehouses reboots monthly
treehouses reboots cron
treehouses remote status
treehouses remote upgrade
treehouses remote services available
treehouses remote services installed
treehouses remote services running
treehouses remote version
treehouses remote commands
treehouses rename
treehouses restore
treehouses rtc on
treehouses rtc on rasclock
treehouses rtc on ds3231
treehouses rtc off
treehouses sdbench
treehouses speedtest
treehouses speedtest -h
treehouses ssh on
treehouses ssh off
treehouses sshkey add
treehouses sshkey list
treehouses sshkey delete
treehouses sshkey deleteall
treehouses sshkey github adduser
treehouses sshkey github deleteuser
treehouses sshkey github addteam
treehouses sshtunnel add
treehouses sshtunnel remove
treehouses sshtunnel list
treehouses sshtunnel check
treehouses sshtunnel key
treehouses sshtunnel notice
treehouses sshtunnel notice on
treehouses sshtunnel notice off
treehouses sshtunnel notice add
treehouses sshtunnel notice delete
treehouses sshtunnel notice list
treehouses sshtunnel notice now
treehouses staticwifi
treehouses temperature
treehouses temperature fahrenheit
treehouses temperature celsius
treehouses timezone
treehouses tor add
treehouses tor list
treehouses tor status
treehouses tor refresh
treehouses tor stop
treehouses tor delete
treehouses tor start
treehouses tor
treehouses tor notice on
treehouses tor notice off
treehouses tor notice now
treehouses tor notice add
treehouses tor notice delete
treehouses tor notice list
treehouses tor deleteall
treehouses tor destroy
treehouses upgrade
treehouses upgrade --check
treehouses upgrade -f
treehouses usb on
treehouses usb off
treehouses verbose
treehouses verbose on
treehouses verbose off
treehouses version
treehouses vnc
treehouses vnc off
treehouses vnc on
treehouses vnc info
treehouses wifi
treehouses wificountry
treehouses wifihidden
treehouses wifistatus
EOF
}

complete -F _treehouses_complete treehouses
