#!/bin/bash

# create ntopng.yml
mkdir -p /srv/ntopng
{
  echo "services:"
  echo "  ntopng:"

  echo "    image: jonbackhaus/ntopng"
  echo "    ports:"
  echo "      - \"8090:8090\""
  echo "    volumes:"
  echo "      - \"/var/run/docker.sock:/var/run/docker.sock\""
  echo "      - \"/ntopng_data:/data jonbackhaus/ntopng\"
  echo "version: \"2\""
  echo "volumes:"
  echo "  ntopng_data:"
} > /srv/ntopng/ntopng.yml
