name: new version

on:
  push:
#    tags:
#      - '*.*.*'

jobs:
  build:
    name: treehouses/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: build
        run: |
          ./templates/blocker/blocker.sh
          ls -al ./templates/blocker/
          sudo npm install -g auto-changelog
          auto-changelog --version
          auto-changelog --template .github/workflows/changelog-template.hbs
          sync
          sed -i -e "s#&lt;#<#g" CHANGELOG.md
          sed -i -e "s#&gt;#>#g" CHANGELOG.md
          ls -al
#      - name: release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          body: |
#            ${{ github.event.head_commit.message }}
#          draft: false
#          prerelease: false
#      - name: publish
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: report
        run: |
          sudo npm install -g @treehouses/cli
          export discord_channel="${{ secrets.CHANNEL }}"
#          https://www.npmjs.com/package/@treehouses/cli/v/1.26.10
